# Generated by Django 2.2.1 on 2019-05-11 15:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VerifyCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, verbose_name='验证码')),
                ('phone_num', models.CharField(max_length=11, verbose_name='电话')),
                ('add_time', models.DateField(default=datetime.datetime.now, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '短信验证码',
                'verbose_name_plural': '短信验证码',
            },
        ),
        migrations.RenameField(
            model_name='user',
            old_name='userCreateTime',
            new_name='user_create_time',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='userPhoneNumber',
            new_name='user_phone_number',
        ),
        migrations.RemoveField(
            model_name='user',
            name='userType',
        ),
        migrations.AddField(
            model_name='user',
            name='user_type',
            field=models.IntegerField(choices=[(0, '顾客'), (1, '管理员'), (2, '厨师'), (3, '服务员')], default=1, verbose_name='用户类型'),
        ),
    ]
