# Generated by Django 2.2.1 on 2019-05-15 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='verifycode',
            name='is_register',
        ),
        migrations.AddField(
            model_name='verifycode',
            name='purpose',
            field=models.IntegerField(choices=[(0, '注册'), (1, '登录'), (2, '修改密码')], default=0, verbose_name='验证码的用途'),
        ),
    ]
