# Generated by Django 2.2.1 on 2019-05-10 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0002_auto_20190510_2047'),
    ]

    operations = [
        migrations.AddField(
            model_name='verifycode',
            name='is_register',
            field=models.BooleanField(default=False, null=True, verbose_name='是否为注册验证码'),
        ),
    ]
