# Generated by Django 2.2.1 on 2019-05-14 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('dish_id', models.IntegerField(primary_key=True, serialize=False, verbose_name='菜品编号')),
                ('dish_name', models.CharField(max_length=128, verbose_name='菜品名称')),
                ('dish_price', models.FloatField(verbose_name='菜品价格')),
                ('dish_type', models.CharField(max_length=30, null=True, verbose_name='菜品分类')),
                ('dish_stock', models.IntegerField(default=999, verbose_name='菜品库存')),
                ('dish_picture', models.TextField(null=True, verbose_name='菜品图片')),
                ('dish_description', models.TextField(null=True, verbose_name='菜品描述')),
                ('dish_add_time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='菜品添加时间')),
            ],
            options={
                'verbose_name': '菜品',
                'verbose_name_plural': '菜品',
            },
        ),
    ]
