# Generated by Django 2.2.1 on 2019-05-14 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dishes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dish',
            name='id',
        ),
        migrations.AlterField(
            model_name='dish',
            name='dish_id',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='菜品编号'),
        ),
    ]
