# Generated by Django 2.2.1 on 2019-05-07 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dishes', '0002_dish_dishaddtime'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dish',
            options={'verbose_name': '菜品', 'verbose_name_plural': '菜品'},
        ),
        migrations.AddField(
            model_name='dish',
            name='dishType',
            field=models.CharField(max_length=30, null=True, verbose_name='菜品分类'),
        ),
    ]
