# Generated by Django 2.2.1 on 2019-05-11 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DiningTable',
            fields=[
                ('tableId', models.AutoField(primary_key=True, serialize=False, verbose_name='餐桌编号')),
                ('tableCategory', models.IntegerField(choices=[(0, '大桌'), (1, '中桌'), (2, '小桌')], default=1, verbose_name='餐桌类别')),
                ('tableState', models.IntegerField(choices=[(0, '空闲'), (1, '占用')], default=0, verbose_name='餐桌状态')),
                ('bookTime', models.DateTimeField(auto_now_add=True, verbose_name='预定时间')),
            ],
            options={
                'verbose_name': '餐桌',
                'verbose_name_plural': '餐桌',
            },
        ),
    ]
