# Generated by Django 2.2.1 on 2019-05-11 21:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Tables', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booktime',
            name='book_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='顾客'),
        ),
        migrations.AddField(
            model_name='booktime',
            name='table',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tables.Table', verbose_name='餐桌'),
        ),
    ]
