# Generated by Django 2.2.1 on 2019-05-15 16:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Tables', '0002_auto_20190514_1946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booktime',
            name='book_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_user', to=settings.AUTH_USER_MODEL, verbose_name='顾客'),
        ),
        migrations.AlterField(
            model_name='booktime',
            name='table',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='table', to='Tables.Table', verbose_name='餐桌'),
        ),
    ]
