# Generated by Django 2.2.1 on 2019-05-11 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tables', '0003_auto_20190511_1033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diningtable',
            name='bookTime',
            field=models.DateTimeField(blank=True, null=True, verbose_name='预定时间'),
        ),
    ]
