# Generated by Django 2.2.1 on 2019-05-05 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('userId', models.AutoField(primary_key=True, serialize=False, verbose_name='用户编号')),
                ('userName', models.CharField(max_length=64, verbose_name='用户名')),
                ('userPhoneNumber', models.CharField(max_length=20, unique=True, verbose_name='用户手机号码')),
                ('userCreateTime', models.DateTimeField(auto_now_add=True, null=True, verbose_name='用户创建时间')),
                ('userType', models.IntegerField(default=1, verbose_name='用户类型')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
