# Generated by Django 2.2.1 on 2019-05-05 15:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('announcementId', models.AutoField(primary_key=True, serialize=False, verbose_name='公告编号')),
                ('announcementContent', models.TextField(null=True, verbose_name='公告内容')),
                ('announcementPublishTime', models.DateTimeField(auto_now_add=True, verbose_name='公告发布时间')),
                ('announcementModifyTime', models.DateTimeField(auto_now=True, verbose_name='公告修改时间')),
                ('announcementModifyUser', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Users.User')),
            ],
        ),
    ]
