# Generated by Django 2.2.1 on 2019-05-07 02:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Announcements', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='announcement',
            options={'verbose_name': '公告', 'verbose_name_plural': '公告'},
        ),
    ]
