# Generated by Django 2.2.1 on 2019-05-15 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Announcements', '0002_announcement_announcementmodifyuser'),
    ]

    operations = [
        migrations.RenameField(
            model_name='announcement',
            old_name='announcementId',
            new_name='announcement_id',
        ),
        migrations.RenameField(
            model_name='announcement',
            old_name='announcementModifyTime',
            new_name='announcement_modify_time',
        ),
        migrations.RenameField(
            model_name='announcement',
            old_name='announcementModifyUser',
            new_name='announcement_modify_user',
        ),
        migrations.RenameField(
            model_name='announcement',
            old_name='announcementPublishTime',
            new_name='announcement_publish_time',
        ),
        migrations.RemoveField(
            model_name='announcement',
            name='announcementContent',
        ),
        migrations.AddField(
            model_name='announcement',
            name='announcement_content',
            field=models.TextField(blank=True, null=True, verbose_name='公告内容'),
        ),
        migrations.AddField(
            model_name='announcement',
            name='announcement_picture',
            field=models.TextField(blank=True, null=True, verbose_name='公告图片'),
        ),
    ]
