# Generated by Django 2.2.1 on 2019-05-12 16:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Dishes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False, verbose_name='订单编号')),
                ('order_time', models.DateTimeField(auto_now_add=True, verbose_name='下单时间')),
                ('order_pay_time', models.DateTimeField(blank=True, null=True, verbose_name='付款时间')),
                ('order_process_time', models.DateTimeField(blank=True, null=True, verbose_name='处理时间')),
                ('order_finish_time', models.DateTimeField(blank=True, null=True, verbose_name='完成时间')),
                ('order_confirm_time', models.DateTimeField(blank=True, null=True, verbose_name='确认时间')),
                ('order_price', models.FloatField(verbose_name='订单金额')),
                ('order_script', models.TextField(null=True, verbose_name='订单留言')),
                ('order_status', models.IntegerField(choices=[(0, '已取消'), (1, '已下单'), (2, '已支付'), (3, '处理中'), (4, '已完成'), (5, '已确认')], verbose_name='订单状态')),
                ('pay_method', models.IntegerField(choices=[(0, '支付宝'), (1, '微信支付')], verbose_name='支付方式')),
                ('table_ware_num', models.IntegerField(verbose_name='餐具份数')),
                ('check_info', models.TextField(blank=True, null=True, verbose_name='发票信息')),
                ('trade_info', models.TextField(blank=True, null=True, verbose_name='交易信息')),
            ],
            options={
                'verbose_name': '订单',
                'verbose_name_plural': '订单',
            },
        ),
        migrations.CreateModel(
            name='OrderDish',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dish_num', models.IntegerField(verbose_name='点餐数量')),
                ('dish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Dishes.Dish', verbose_name='菜品')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Orders.Order', verbose_name='订单编号')),
            ],
            options={
                'verbose_name': '订单菜品',
                'verbose_name_plural': '订单菜品',
            },
        ),
        migrations.AddField(
            model_name='order',
            name='order_dishes',
            field=models.ManyToManyField(through='Orders.OrderDish', to='Dishes.Dish', verbose_name='订单菜品'),
        ),
    ]
