# Generated by Django 2.2.1 on 2019-05-12 11:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Dishes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('orderId', models.AutoField(primary_key=True, serialize=False, verbose_name='订单编号')),
                ('orderTime', models.DateTimeField(auto_now_add=True, verbose_name='下单时间')),
                ('orderPayTime', models.DateTimeField(verbose_name='付款时间')),
                ('orderProcessTime', models.DateTimeField(verbose_name='处理时间')),
                ('orderFinishTime', models.DateTimeField(verbose_name='完成时间')),
                ('orderConfirmTime', models.DateTimeField(verbose_name='确认时间')),
                ('orderPrice', models.FloatField(verbose_name='订单金额')),
                ('orderScript', models.TextField(null=True, verbose_name='订单留言')),
                ('orderStatus', models.IntegerField(choices=[(0, '已取消'), (1, '已下单'), (2, '已支付'), (3, '处理中'), (4, '已完成'), (5, '已确认')], verbose_name='订单状态')),
            ],
            options={
                'verbose_name': '订单',
                'verbose_name_plural': '订单',
            },
        ),
        migrations.CreateModel(
            name='OrderDish',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dishNum', models.IntegerField(verbose_name='下单数量')),
                ('dish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Dishes.Dish', verbose_name='菜品')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Orders.Order', verbose_name='订单编号')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='orderDishes',
            field=models.ManyToManyField(through='Orders.OrderDish', to='Dishes.Dish', verbose_name='订单菜品'),
        ),
    ]
