# Generated by Django 2.2.1 on 2019-05-11 17:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Orders', '0001_initial'),
        ('Tables', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='orderTable',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tables.Table', verbose_name='订单餐桌'),
        ),
    ]
