# Generated by Django 2.2.1 on 2019-05-14 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Orders', '0003_order_order_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderdetail',
            old_name='order_id',
            new_name='order',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='order_id',
            new_name='order',
        ),
    ]
