# Generated by Django 2.2.1 on 2019-05-11 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Orders', '0003_order_orderuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='orderStatus',
            field=models.IntegerField(choices=[(0, '已取消'), (1, '已下单'), (2, '已支付'), (3, '处理中'), (4, '已完成'), (5, '已确认')], verbose_name='订单状态'),
        ),
    ]
