# Generated by Django 2.2.1 on 2019-05-15 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Orders', '0006_auto_20190515_1456'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transaction',
            options={'verbose_name': '交易信息', 'verbose_name_plural': '交易信息'},
        ),
    ]
